#Name error occurs when we are tyring to use a variable without declaring it priori

print(name)
#the above line will throw an error as we have not defined what name is 

name="Bellatrix"
print(name)
#this will now work as we have defined what name means 

#NameError will also occur for function definitions